Sprint-3
nivanov045/silver-octo-train pull request #16
Opened 2022-08-18 09:20 UTC by nivanov045

2022-08-18 12:14 UTC, rktkov requested changes

2022-08-18 12:14 UTC, rktkov commented on cmd/server/storage/storage.go
> +	is InnerStorage
Имя для поля лучше выбрать более "говорящее"

2022-08-18 12:14 UTC, rktkov commented on cmd/server/storage/storage.go
> +func New(storeInterval time.Duration, storeFile string, restore bool, databasePath string) *storage {
А может сюда принять экземпляр конфига, где будут все необходимые данные лежать. Ведь мы не исключаем ситуацию, что могут появиться дополнительные опции запуска.

2022-08-18 12:14 UTC, rktkov commented on cmd/server/storage/dbstorage/dbstorage.go
> +	runtime.SetFinalizer(res, storageFinalizer)
Если функция storageFinalizer вызывается только здесь, то лучше анонимную функцию написать.

2022-08-18 12:14 UTC, rktkov commented on cmd/server/storage/dbstorage/dbstorage.go
> +		`SELECT EXISTS (SELECT FROM information_schema.tables WHERE  table_name = 'metrics');`)
Может тексты запросов сделать константами и вынести в начало файла. Кажется это сделает код более "читабельным".

2022-08-18 12:14 UTC, rktkov commented on cmd/server/storage/dbstorage/dbstorage.go
> +			log.Panic("DBStorage::New::error: in table creation:", err)
А мы точно хотим кидать панику, если ошибки инициализации БД? У нас ведь есть альтернативные способы хранения. Я бы возвращал ошибку и предлагал бы клиенту принимать решение, готов ли он работать без БД или нет.

2022-08-18 12:14 UTC, rktkov commented on cmd/server/storage/dbstorage/dbstorage.go
> +		log.Println("DBStorage::SetCounterMetrics::error: in ExecContext:", err)
Я бы не замалчивал ошибку и возвращал бы ее клиенту.

2022-08-18 12:14 UTC, rktkov commented on cmd/server/storage/dbstorage/dbstorage.go
> +		log.Println("DBStorage::SetGaugeMetrics::error: in ExecContext:", err)
см. комменатрий выше про тихую ошибку

2022-08-18 12:14 UTC, rktkov commented on cmd/server/storage/inmemorystorage/inmemorystorage.go
> +func StorageFinalizer(s *InMemoryStorage) {
Этот метод действительно используется где-то еще кроме пакета?

2022-08-18 12:14 UTC, rktkov commented on cmd/server/server.go
> +	myStorage := storage.New(cfg.StoreInterval, cfg.StoreFile, cfg.Restore, cfg.Database)
Вот тут было бы изящнее cfg передать инициализатору.

2022-08-18 12:14 UTC, rktkov commented on cmd/server/server.go
> +	myStorage := storage.New(cfg.StoreInterval, cfg.StoreFile, cfg.Restore, cfg.Database)
Вот тут было бы изящнее cfg передать инициализатору.

2022-08-23 14:40 UTC, rktkov approved these changes

2022-08-23 14:40 UTC, rktkov commented on cmd/agent/metricsagent/metricsagent.go
> +					//log.Println("metricsagent::sendMetrics::info: hash", hash)
Не нужный код лучше удалять, а не комментировать.

2022-08-23 14:40 UTC, rktkov commented on cmd/agent/metricsagent/metricsagent.go
> +				//log.Println("metricsagent::sendMetrics::info: hash", hash)
см. комментарий выше
и стоит это сделать дальше по всему коду, отдельный комментарий не буду добавлять.

2022-08-23 14:40 UTC, rktkov commented on cmd/agent/metricsagent/metricsagent.go
> +				log.Panicln("metricsagent::sendSeveralMetrics::error: can't marshal PollCount metric for sand with", err)
Опять паника в месте, где лучше использовать ошибку.

2022-08-23 14:40 UTC, rktkov commented on cmd/agent/requester/requester.go
> +		log.Panicln("requester::Send::error: can't create request with:", err)
Зачем в сигнатуре метода возвращаемый аргумент ошибка, если ты их не возвращаешь, панику генерируешь. Лучше залогировать и вернуть ошибку. Дальше по коду стоит изменить такое поведение. Если где-то его не надо будет менять, я прокомментирую.

2022-08-23 14:40 UTC, rktkov commented on cmd/agent/requester/requester.go
> +		log.Println("requester::Send::error: can't do request:", err)
Вот тоже стоит ошибку вернуть выше, либо ту, которую словил, либо заверни ее в какую-то новую, но клиенту верни. Не стоит ошибки "замалчивать".

2022-08-23 14:40 UTC, rktkov commented on cmd/server/server.go
> +	myStorage, err := storage.New(cfg)
А вот тут красиво бы смотрелось что-то похожее на "фабрику" слоя хранения, где бы ты осуществлял все необходимые проверки и выбирал нужную реализацию хранилища. Это предложение на улучшение, не требование.

2022-08-23 14:40 UTC, rktkov commented on cmd/server/service/service.go
> +		if !ser.checkHash(m) {
Стоит подумать о том, как унести проверку хеша выше по стеку вызова. Можем ли мы этот код поместить,  например в  middleware обработки запроса? Предложение, не призыв к действию.

2022-08-23 14:40 UTC, rktkov commented on cmd/server/service/service.go
> +func (ser *service) checkHash(m metrics.Interface) bool {
Стоит вынести этот код в отдельный пакет, который бы реализовывал все криптографические функции.

2022-08-24 09:54 UTC, nivanov045 commented on cmd/agent/metricsagent/metricsagent.go
> +				log.Panicln("metricsagent::sendSeveralMetrics::error: can't marshal PollCount metric for sand with", err)
Но ведь это происходит внутри горутины и если верно понимаю, то не стоит что-то пытаться получить из нее (даже ошибку). Просто завершать ее, оставляя запись в логе?

2022-08-24 10:02 UTC, nivanov045 commented on cmd/server/server.go
> +	myStorage, err := storage.New(cfg)
А в чем отличие от того, как сделано? `server` не задумывается о хранении и передает конфиг `storage`, который внутри определяет, какой тип хранилища использовать исходя из конфига.

2022-08-24 10:36 UTC, merged