increment3: Handle of new address was added.
nivanov045/silver-octo-train pull request #3
Opened 2022-07-10 04:20 UTC by nivanov045

2022-07-13 10:37 UTC, rktkov requested changes
Оставшийся код буду смотреть в следующем инкременте, когда увижу другие файлы.

2022-07-13 10:37 UTC, rktkov commented on internal/metrics/metrics.go
> +var KnownMetrics = [...]string{
Имена полей в структуре метрик выбраны плохо, они должны быть понятными.

2022-07-13 10:37 UTC, rktkov commented on cmd/server/storage/storage.go
> +func (s *storage) GetCounterMetrics(name string) (met.Counter, bool) {
Псевдоним в данном случае хуже имени пакета, я бы его не вводил

2022-07-13 10:37 UTC, rktkov commented on cmd/server/storage/storage.go
> +func (s *storage) GetCounterMetrics(name string) (met.Counter, bool) {
Имя поля в структуре storage тоже стоит сделать более "говорящим".

2022-07-13 10:37 UTC, rktkov commented on cmd/server/service/service.go
> +
Методы инициализаторы структур стоит называть New<StructName>

2022-07-13 10:37 UTC, rktkov commented on cmd/server/service/service.go
> +func (ser *service) ParseAndSave(s string) error {
Строковые имена типов метрик можно сделать константами, а еще лучше ввести перечисление, в котором будут строковые значения.

2022-07-13 10:37 UTC, rktkov commented on cmd/server/service/service.go
> +func (ser *service) ParseAndSave(s string) error {
Так же для читабильности кода, я бы ввел отдельные переменные, которым бы присвоил значения после разделения строки.

2022-07-13 10:37 UTC, rktkov commented on cmd/server/service/service.go
> +	ss := strings.Split(s, "/")
См. комментарии выше про внутренние переменные.

2022-07-13 10:37 UTC, rktkov commented on cmd/server/api/api.go
> +	GetKnownMetrics() []string
Комментарий к строчке 21. Название инициализирующего метода

2022-07-13 10:37 UTC, rktkov commented on cmd/server/api/api.go
> +		w.WriteHeader(http.StatusNotFound)
Код 404 обычно возвращается, когда сервер не может обработать присланный  url. Я бы возвращал BadRequest. И вообще на все возможные ошибки, можно вернуть этот код ответа, а в сообщение уже помещать детали ошибки, если необходимо о ней рассказать клиенту. Этот же комментарий можно и к методу выше применить.

2022-07-14 01:55 UTC, nivanov045 commented on cmd/server/service/service.go
> +
Так и сделано для всех структур. GetKnownMetrics не инициализатор, а запрос к бд списка всех доступных на данный момент метрик.

2022-07-14 02:34 UTC, nivanov045 commented on cmd/server/api/api.go
> +	GetKnownMetrics() []string
Не понял в 21 строке стоит New в названии инициализирующего метода. Это неверно?

2022-07-14 02:46 UTC, nivanov045 commented on cmd/server/api/api.go
> +		w.WriteHeader(http.StatusNotFound)
Понял, учту на будущее. Но по ТЗ 
`При попытке запроса неизвестной серверу метрики сервер должен возвращать http.StatusNotFound.`
, так что если реализую как предложено, не пройдут тесты. И в методе выше тоже делал по ТЗ.

2022-07-14 10:06 UTC, rktkov commented on cmd/server/api/api.go
> +		w.WriteHeader(http.StatusNotFound)
Понял. Вопрос снят.

2022-07-14 10:13 UTC, rktkov approved these changes
ПР принял, но в следующий раз жду изменения логики взаимодействия в коде агента.

2022-07-14 10:13 UTC, rktkov commented on cmd/agent/agent.go
> +		fmt.Println("Reported ", m.CounterMetrics["PollCount"])
Комментарий к следующей строчке - 48. 
Логика передачи 1 экземпляра метрики между 2 горутинами мне не нравиться. При такой реализации частота выполнения действий будет равно самому длинному интервалу из 2-х. Ведь по факту, таким образом переходит передача выполнения между горутинами.

2022-07-14 10:53 UTC, nivanov045 commented on cmd/agent/agent.go
> +		fmt.Println("Reported ", m.CounterMetrics["PollCount"])
Лучшее, что приходит в голову вместо этого - добавить в агента поле, куда метрики будут сохраняться при обновлении и откуда будут браться при отправке. Даже можно не защищать поле мьютексом при записи - так как пишет всего один метод, второй же только читает.

2022-07-14 10:55 UTC, merged