Sprint 2
nivanov045/silver-octo-train pull request #9
Opened 2022-08-01 12:57 UTC by nivanov045

2022-08-01 15:51 UTC, rktkov requested changes

2022-08-01 15:51 UTC, rktkov commented on cmd/server/storage/storage.go
> +		s.saveToFile()
Никак не обрабатывается возможная ошибка при сохранении в файл.

2022-08-01 15:51 UTC, rktkov commented on cmd/server/storage/storage.go
> +		s.saveToFile()
Никак не обрабатывается возможная ошибка при сохранении в файл.

2022-08-01 15:51 UTC, rktkov commented on cmd/server/storage/storage.go
> +func New(storeInterval time.Duration, storeFile string, restore bool) *storage {
Обычно, функции инициализаторы пишутся сразу после объявления структуры.

2022-08-01 15:51 UTC, rktkov commented on cmd/server/storage/storage.go
> +	file, err := os.OpenFile(s.storeFile, os.O_WRONLY|os.O_CREATE, 0777)
Так как есть как минимум 2 места, которы могут обратиться к файлу в общем случае одновременно, то получается файл является разделяемым ресурсом, возможно стоит подумать о его защите.

2022-08-01 15:51 UTC, rktkov commented on cmd/agent/agent.go
> +	flag.StringVar(&cfg.Address, "a", "127.0.0.1:8080", "address")
Конфигурация приложения и дальше будет расширяться, поэтому стоит вынести все что связанно с ее обработкой в отдельный пакет.

2022-08-01 15:51 UTC, rktkov commented on cmd/agent/metricsagent/metricsagent.go
> +func (a *metricsagent) updateMetrics() {
Не предусмотрен способ корректного завершения работы горутины.

2022-08-01 15:51 UTC, rktkov commented on cmd/agent/metricsagent/metricsagent.go
> +func (a *metricsagent) sendMetrics() {
Не предусмотрен способ корректного завершения работы горутины.

2022-08-01 15:51 UTC, rktkov commented on cmd/agent/metricsagent/metricsagent.go
> +func (a *metricsagent) sendMetrics() {
Взаимодействие между 2-мя горутинами через использование общей памяти - a.Metrics -не очень гошный способ организации обмена данными. Более того, при таком способе при задании определенных условий, часть данных будет теряться.
Стоит переписать взаимодействие с учетом использования каналов, как основного инструмента.

2022-08-03 02:56 UTC, nivanov045 commented on cmd/agent/metricsagent/metricsagent.go
> +func (a *metricsagent) sendMetrics() {
Единственное, что придумал с учетом этого комментария и из прошлого pr (https://github.com/nivanov045/silver-octo-train/pull/3#discussion_r920990543) - иметь вместо общей памяти общий канал, откуда читать-возвращать значение сразу, чтобы не было задержек.

2022-08-04 21:30 UTC, rktkov approved these changes

2022-08-04 21:30 UTC, rktkov commented on cmd/agent/agentconfig/agentconfig.go
> +package agentconfig
Пакет уже находится в дереве, где есть слово agent, т.е. его можно называть config. Тоже относится и к серверу.

2022-08-08 06:27 UTC, merged